"""timestamp

Revision ID: e0ed7dbf5d4c
Revises: a820b832e027
Create Date: 2023-10-30 00:13:49.280694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0ed7dbf5d4c"
down_revision: Union[str, None] = "a820b832e027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("contacts", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "updated_at")
    op.drop_column("contacts", "created_at")
    # ### end Alembic commands ###
